name: video_converter
description: Convert any video file to MP4 or MOV, right from your desktop.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.5.0
  cross_file: ^0.3.4+2
  file_picker: ^8.1.2
  path: ^1.9.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 256
